### ISSUE TITLE
Error when a dictionary's key has '/' in it

### ISSUE THREAD

**Issue by choldgraf** [h5io/h5io#10]
If you write an HDF5 file that includes a dictionary with a `/` in the keys, then reading won't work. I looked through the code and basically what happens is that `_triage_write` calls `root.create_group(key)`, and if there's a `/` in key, then is splits into two groups instead of a single group w/ `/` in the key. I'm guessing this is some kind of default h5py behavior.

So would it make more sense to:

1. Check if the person has input a `/` under the `isinstance(dict)` part of `_triage_write` and throw an error if so

or

2. Automatically replace that value with something that we can then re-replace during read. E.g.:

```python
special_chars = {'{BACKSLASH}': '/'}

def _create_titled_group(root, key, title):
    """Helper to create a titled group in h5py"""
    # Auto-replace keys with proper values
    for key_spec, val_spec in special_chars.items():
        key = key.replace(val_spec, key_spec)
    out = root.create_group(key)
    out.attrs['TITLE'] = title
    return out

def _triage_read(node):
    h5py = _check_h5py()
    type_str = node.attrs['TITLE']
    if isinstance(type_str, bytes):
        type_str = type_str.decode()
    if isinstance(node, h5py.Group):
        if type_str == 'dict':
            data = dict()
            for key, subnode in node.items():
                # Auto-replace the keys/values if we find them
                for key_spec, val_spec in special_chars.items():
                    key.replace(key_spec, val_spec)
                data[key[4:]] = _triage_read(subnode)
...
```

**Comment by Eric89GXL** [comment]
Let's do auto-replacement but document it clearly in the docstring, as you're right slashes shouldn't be in there:

http://stackoverflow.com/questions/30070834/in-names-in-hdf5-files-confusion

Actually maybe we should have `slash='error'` by default with `slash='replace'` meaning replace it with '{SLASH}'. Note that `/` is a forward slash BTW.

**Comment by choldgraf** [comment]
Looking into a PR on this but I realized that if you auto-replace forwardslashes then it will mess up situations where you actually *want* h5py to break up the forwardslashes...hmm

**Comment by choldgraf** [comment]
And the main reason that I was hesitant to suggest throwing an error is that dictionaries w/ forwardslashes are a common way for MNE to represent `event: event_type` dictionaries

**Comment by Eric89GXL** [comment]
When would you want to have h5py break up the forwardslashes when writing with `h5io`?

**Comment by choldgraf** [comment]
not sure but one attempt at this broke this test:

```python
def test_path_support():
    tempdir = _TempDir()
    test_file = op.join(tempdir, 'test.hdf5')
    write_hdf5(test_file, 1, title='first')
    write_hdf5(test_file, 2, title='second/third', overwrite='update')  <---- forward slashes in title
    assert_raises(ValueError, read_hdf5, test_file, title='second')
    assert_equal(read_hdf5(test_file, 'first'), 1)
    assert_equal(read_hdf5(test_file, 'second/third'), 2)
```

**Comment by Eric89GXL** [comment]
Ahh, so *only* at the top level, I think. We could work around that use case I think.

**Comment by Eric89GXL** [comment]
(I don't think using forward slashes in lower levels should really be supported, I don't know what it would do...)

**Comment by dengemann** [comment]
I think you need to recode HED style keys internally, like replace them with special characters.

**Comment by choldgraf** [comment]
yeah I agree that it's a bit weird, but that's what the event_id structures are in MNE. If you have more than one type in the structure then it will error. e.g.: `event_id = {'bef/first': 1, 'aft/second': 2}`

**Comment by Eric89GXL** [comment]
I think we should allow forward slashes in the top level, meaning, save to / load from this nested location, and have `slash='error'` (by default) error if any key has a slash in it, and have `slash='replace'` use what you suggest.

**Comment by choldgraf** [comment]
See https://github.com/h5io/h5io/pull/11

thoughts?

**Comment by choldgraf** [comment]
I believe this is fixed, so closing
