### ISSUE TITLE
BUG: np.bool_

### ISSUE THREAD

**Issue by kingjr** [h5io/h5io#12]
I think `np.bool_` is pretty common and should be supported:

`write_hdf5(fname, np.bool_(1))`

currently returns the following error

```
`
/home/jrking/src/h5io/h5io/_h5io.pyc in write_hdf5(fname, data, overwrite, compression, title)
    103         _triage_write(title, data, fid, comp_kw,
    104                       str(type(data)),
--> 105                       cleanup_data=cleanup_data)
    106 
    107     # Will not be empty if any extra data to be written

/home/jrking/src/h5io/h5io/_h5io.pyc in _triage_write(key, value, root, comp_kw, where, cleanup_data)
    166         else:
    167             err_str = 'unsupported type %s (in %s)' % (type(value), where)
--> 168             raise TypeError(err_str)
    169 
    170 ##############################################################################

TypeError: unsupported type <type 'numpy.bool_'> (in <type 'numpy.bool_'>)
```

Note that `np.bool` is supported.

**Comment by kingjr** [comment]
Probably related to https://github.com/numpy/numpy/issues/3530

Not sure we want to address this here

**Comment by Eric89GXL** [comment]
We could support it, it should only be two more lines in the read and write functions.

**Comment by kingjr** [comment]
Ok, I wasn't sure this was suppose to be changed at some point in numpy. Let me try a quick PR

**Comment by Eric89GXL** [comment]
The last activity on that issue is from over two years ago so I wouldn't hold your breath :)

**Comment by kingjr** [comment]
right
