### ISSUE TITLE
hdf5 in pandas

### ISSUE THREAD

**Issue by kingjr** [h5io/h5io#19]
Isn't there a redundancy with pandas?
http://glowingpython.blogspot.com/2014/08/quick-hdf5-with-pandas.html

**Comment by Eric89GXL** [comment]
There is some amount of overlap (storing `numpy`-like objects), but this module is in some ways more general. Actually we recently had a PR to allow inter-operability with Pandas HDF5 objects.

Also this lib is pure python with no real API changes, in conrast with Pandas (which historically has been difficult to maintain compatibility with for MNE).

**Comment by Eric89GXL** [comment]
See also https://github.com/h5io/h5io/pull/5
