### ISSUE TITLE
Implement pandas support

### ISSUE THREAD

**Issue by choldgraf** [h5io/h5io#2]
How tough do you think it'd be to implement pandas support? I'm thinking in the triage functions you could check if it is a pandas dataframe, and if it is just save the file as a list of its component parts, similar to how the pandas `to_hdf` method works. What do you think?

**Comment by Eric89GXL** [comment]
Most things I've tried to implement pandas support for have been tough because their API changed too frequently. That was probably a year or so ago now, so I guess it would depend on how stable they are now. Is there a list of stable component parts that could be used to deconstruct and reconstruct the objects?

**Comment by choldgraf** [comment]
In my experience it's been relatively stable the last year or so. Actually, I wonder if you could just do it using the pandas `to_hdf` method. This just asks for an h5 file path, and a 'key' to store the data. E.g., in the triage, if an object is a dataframe, then you would do `df.to_hdf('./my_hdf.5', 'my_data')`.

Could you just call this method with the key being 'DF_MNE' or something like this? I doubt the dataframe h5 libraries will change too much over time...

Chris

**Comment by Eric89GXL** [comment]
The `to_hdf` sounds like a good approach. Then you get as much forward/backward compatibility for those objects as `pandas` supplies, which is great. I'm not sure how its writing function would interact with the already-opened `hdf5` object/file we have, though. I guess you could delay writing all pandas objects to the end, but that sounds like a pain to keep track of. You might need to close the file, let pandas write, and reopen the file for every write. Clunky but it should work. Hopefully there's a better way.

**Comment by choldgraf** [comment]
I have definitely run into issues with h5io and pandas in the past. Been
meaning to open an issue but I haven't nailed down the bug yet. Basically
occasionally if you open an h5 file in pandas, and then do it with h5io in
some order, then the kernel dies. Maybe that bug would be unearthed if this
were implemented. I can try to take a whack at adding 'dumb' (aka, with
`to_hdf`) dataframe functionality if you like.

**Comment by Eric89GXL** [comment]
I am -1 on adding it if it leads to such instability. To be clear, you mean `h5io`, this library, or `h5py`, the lower-level library that does all the heavy lifting? It sounds like `pandas` and `h5py` don't get along in some way. It's probably worth first making a minimal example where those two libraries don't get along, and then getting one of them to fix the bug.

**Comment by choldgraf** [comment]
fair enough - next time it happens to me I'll try to nail it down, then we
can revisit this if it's something sensible.

**Comment by choldgraf** [comment]
Hey - been looking into this now. I don't think it'd be too tough to incorporate this in the code that's already there. The following works just fine for me:

```python
import h5io
import pandas as pd
import numpy as np
import h5py

# Create some fake data and write it to an HDF5 file
data = np.random.randn(100, 10)
data2 = np.random.randn(100, 5)
alldata = {'a': data, 'b': data2}
h5io.write_hdf5('./data/test_hdf_h5io.h', alldata, overwrite=True)

# More fake data, this time a df
df = pd.DataFrame(np.random.randn(100, 2), columns=['a', 'b'])
df.to_hdf('./data/test_hdf_h5io.h', 'h5io/df_1')

# Open the file to look inside
with h5py.File('./data/test_hdf_h5io.h', 'r') as f:
    ds = f['h5io']
    print(ds.keys())
    
# Finally show that we can read in the dataframe
dfin = pd.read_hdf('./data/test_hdf_h5io.h', 'h5io/df_1')
print(dfin.head())

# Note that we can't read in with h5io now
# it'd get confused at the group type but would be built in
```

So it seems that we could just include a check for whether it's a dataframe or series, keep those until the end, and once we've written to the file with h5py and close it, just run the to_hdf methods of anything that's been kept for the end.

**Comment by choldgraf** [comment]
And I should note that I never got any crashes as I alluded to before. I tried open files in pandas while they were open in h5io etc and it never crashed so..........that must mean that the problem is totally fixed and we will never encounter bugs again, right? right?

**Comment by choldgraf** [comment]
It seems like a tricky thing is "how do you write to an hdf5 file that's already open"?

One thought is something like this: add an extra list called "post_io". This will be returned by triage_write/read. Then, after the `with` statement that uses triage_write, you can add another `for` loop that goes through the `post_io` list. Each iteration of the list should supply the proper information to call whatever IO it's meant for. E.g.: 

At the beginning of the loop, we'd add `cleanup_io = []`

Then inside `_triage_write`:
```python
    elif isinstance(value, pd.DataFrame):
        rootname = root.name
        cleanup_data.append((rootname, key, 'dataframe', value))
```

That would add the necessary pieces for the `to_hdf` method. And then here's the outermost bit (note that we're seeing the tail end of the `with` statement where we return cleanup_data)
```python
    cleanup_data = _triage_write(title, data, fid, comp_kw, str(type(data)))
for rootname, key, title, value in cleanup_data:
    if title == 'dataframe':
        _create_pandas_dataset(fname, rootname+'/'+key, title, value)
```

This could theoretically be extended to any IO system that won't work with an already-open file.

I guess a challenge with this is that `_triage_write` kind of implies that it's doing all of the necessary legwork, while this implementation basically says "not always". But I don't see how to do this otherwise, unless we just do custom pandas I/O stuff (e.g., [here](http://stackoverflow.com/questions/30773073/save-pandas-dataframe-using-h5py-for-interoperabilty-with-other-hdf5-readers))

**Comment by Eric89GXL** [comment]
Maybe instead of `cleanup_data` we could call it `other_data` (meaning, data not saved/read by `h5io`). I'm a bit confused how come you need a `isinstance(value, pd.Dataframe)` in the `_triage_write` code. Wouldn't the `other_data` take a completely different writing path?

You say you can't read the `hdf5` file anymore with `read_hdf5` once you've also saved the Pandas data in there, how come?

**Comment by choldgraf** [comment]
> Maybe instead of cleanup_data we could call it other_data (meaning, data not saved/read by h5io).

Good idea - sounds fine to me.

> I'm a bit confused how come you need a isinstance(value, pd.Dataframe) in the _triage_write code. Wouldn't the other_data take a completely different writing path?

Well it's going to the same file, and might be nested inside of other structures like dictionaries, which is why I was putting it in triage write. E.g. I often save my data in a dict like `{'subject': 'sub1', 'experiment': 'exp_a', 'data': dataframe_of_my_data}`. If it's in triage_write then we can point the pandas `to_hdf` method to the specific root of the hdf5 we want.

> You say you can't read the hdf5 file anymore with read_hdf5 once you've also saved the Pandas data in there, how come?

Because it's stored under the h5io group, so when h5io does `read_hdf5` it will find the pandas object and raise an error since it's not implemented right now.

**Comment by Eric89GXL** [comment]
Can you put down what you think the calls should look like to incorporate Pandas data, then? I thought at first you wanted to be able to write pandas data in its own directory in the HDF5 file, but now I realize you're thinking of having pandas data be written to/read from by h5io instead (being careful about making sure it's an optional dependency of course :) ).

To avoid changing the API, we might need a `return_other_data=False` kwarg, that you'd need to set to `True` in order to deal with Pandas data properly. But it depends on if I'm thinking of the API correctly.

**Comment by Eric89GXL** [comment]
For example let's say I want to save my `data = dict(a=1., b=some_pandas_data_frame)` to h5io, and get the result back from disk (this is a minimal type example of your use case right?). How do you propose to do it?

**Comment by choldgraf** [comment]
Let me put together a PR and see what you think about it. Shouldn't take too much time (famous last words)

**Comment by choldgraf** [comment]
So trying to implement it makes me realize one challenge with having this sort of approach:

_triage_write operates in a sort of weird iterative way. It doesn't just loop through all of the pathways in the output hdf5 file. If it finds a list, tuple, dict, etc, then it calls itself once more. This means that we can't just have a `cleanup_data` attribute that we append to, because you'd get namespace collisions when a loop would call that function again.

All that is to say - I wonder if I am making things too complicated. What if instead of writing in native pandas functionality, we could basically just skip over pandas objects when using `read_hdf`? It is possible to read / write pandas objects to an HDF5 file on top of h5io. So we could assume that the user will handle their own pandas writing (they can place it to whatever key they want within the object).

So I think there are 3 options, in order of decreasing complexity/work:

## Option 1 (most difficult)
Add full pandas support along the lines of what we've discussed already. 

## Option 2
Let pandas objects be stored w/in the root/node structure of the h5io data, but skip over them when doing reading.

Include an `allowed_classes` parameter to `_triage_read`. When reading the data, if a node isn't in the classes within the _triage_write loop, check if its type is in the `allowed_classes` list. If so, don't return an error. That way you could still write out the data.

So the syntax would be:

`h5io.read_hdf5(my_file, allowed_classes=[pd.DataFrame])`

and then at the end of `_triage_read`, you could add an extra check to the loop:

```python
elif type_str == 'None':
    data = None
elif type in allowed_types:
    ...allow it to pass
else:
     raise TypeError('Unknown node type: {0}'.format(type_str))
``` 

The trick here is that h5io uses `type_str` not the class itself, so it would error when it first looks for the `TITLE` attribute.


## Option 3 (least work)
Assume that the person will store pandas objects completely independently of the h5io nodes but maybe in the same file. In this case, I think the only change that should be made is to case "overwrite" to not overwrite the whole file, but just the root that is provided to write_hdf5. Otherwise if someone writes pandas, then someone writes h5io stuff with overwrite==True, it will overwrite the whole file.

Thus, you could do
```python
h5io.write_hdf(my_file)
df.to_hdf(my_file, 'pandas/data')
```

At this point I'm kind of partial to 3, as it accomplishes something close with minimal overhead. What do you think?

**Comment by choldgraf** [comment]
Though probably 2 wouldn't be too much extra work. At the beginning of _triage_read, you could just do:

```python
try:
    type_str = node.attrs['TITLE']
except IOError:
   if 'pandas_type' in node.attrs.keys():
       pass
   else
       raise IOError('Unsupported type etc etc')
```

**Comment by Eric89GXL** [comment]
> _triage_write operates in a sort of weird iterative way. It doesn't just loop through all of the pathways in the output hdf5 file. If it finds a list, tuple, dict, etc, then it calls itself once more. This means that we can't just have a cleanup_data attribute that we append to, because you'd get namespace collisions when a loop would call that function again.

It operates recursively, which should be fine. For example you can add an argument `other_data` to the `_triage_read` function. The first call would set it to `other_data=list()`, and any subsequent recursive call would just do `other_data.append(...)`. Same would be true of `_triage_write`.

**Comment by choldgraf** [comment]
Recursive! That was the word I was looking for yesterday. The best I could come up with was "weird iterative" haha.

I had actually started doing that before (with passing a container to the read/write functions), but didn't finish building it in because it seemed like it might clutter things up too much and you seemed like you didn't want to make very drastic changes. If however that sounds OK with you, then I'm happy to give it a shot.

**Comment by dengemann** [comment]
What's the benefit here? Pandas folks have already developed and maintained for long time .to_hdf
Why reinvent things?

**Comment by choldgraf** [comment]
So this would actually use `to_hdf` under the hood...it would just place the dataframe at the proper root/node in the hdf5 file (e.g., if you passed a dictionary and w/in the dictionary was a dataframe). The trick is that you have to run to_hdf on a closed file, so the actual writing can't be done in the `_triage_write` function.

**Comment by Eric89GXL** [comment]
I think you'd have to change every line where `_triage_read` or `_triage_write` gets called. It will look ugly but conceptually it's a small change.

**Comment by choldgraf** [comment]
ok cool - glad I didn't delete the branch where I was trying that then :) I'll make a PR and we can see how it looks.

**Comment by choldgraf** [comment]
Check out #5 for a first pass at _triage_write

**Comment by choldgraf** [comment]
![image](https://cloud.githubusercontent.com/assets/1839645/11914281/343cf03a-a631-11e5-852c-b80bc8153fa3.png)

Thanks for your help one this one @Eric89GXL!
