### ISSUE TITLE
deepdish

### ISSUE THREAD

**Issue by choldgraf** [h5io/h5io#23]
You guys hear about this?

https://github.com/uchicago-cs/deepdish

Seems quite related and pretty nice:

http://deepdish.readthedocs.io/en/latest/io.html

**Comment by Eric89GXL** [comment]
Nope, haven't heard of it. Looks like it does the same thing. Unfortunately it's probably not trivial to switch

**Comment by choldgraf** [comment]
yep - just noting its existence! it looks like their API is almost the same as h5io. Pavan told me about it at the sprint
