### ISSUE TITLE
unsupported type <class 'numpy.int64'>

### ISSUE THREAD

**Issue by fraimondo** [h5io/h5io#24]
Yes, it is an error, since `np.int64` is not instance of `int`.

I added a manual fix in `_triage_read` and `_triage_write` for `np.int64` type, you want it?

**Comment by larsoner** [comment]
The solution should probably be made general enough to handle any `np.*` type, e.g. `np.uint8` as well

**Comment by fraimondo** [comment]
`np.float128` is not supported by the underlying library, but all the rest are now supported. Sending PR including tests.

**Comment by drammock** [comment]
this was addressed in #25 but didn't auto-close.  closing.
