### ISSUE TITLE
Can't install from pip?

### ISSUE THREAD

**Issue by choldgraf** [h5io/h5io#27]
`pip install h5io` isn't working for me. Have we removed it from pip? I thought it used to work...

**Comment by larsoner** [comment]
I don't think we have ever done pip, just included in repositories directly
or installed from git (possibly with pip). We could do a release if it
would help though.

**Comment by choldgraf** [comment]
well it does say here: https://github.com/h5io/h5io#install-h5io

that you can install from pip :-)

also I find h5io pretty useful for quick I/O!

**Comment by larsoner** [comment]
Pushed to pypi, feel free to try it

**Comment by choldgraf** [comment]
worked for me! (ps, have you tried [flit](http://flit.readthedocs.io/en/latest/)? It's pretty nifty!
