### ISSUE TITLE
Version management

### ISSUE THREAD

**Issue by jan-janssen** [h5io/h5io#32]
Would it be reasonable to update the pip and conda-forge versions automatically based on the git tag? 
I personally use https://github.com/warner/python-versioneer . Every release is tagged in git, resulting in the corresponding pip package being an release candidate which triggers the conda forge package update. A sample repository would be: https://github.com/pyiron/pyiron_base with the release history https://pypi.org/project/pyiron-base/#history and the corresponding released on GitHub https://github.com/pyiron/pyiron_base/releases as well as https://anaconda.org/conda-forge/pyiron_base/files

**Comment by larsoner** [comment]
Sounds fine to me but no time to do it. Can you take care of this integration if I give you push permissions?

**Comment by jan-janssen** [comment]
Sure, I guess you only need to link travis with pip afterwards so the release is pushed to pip when the tests on the master branch finish successful.

**Comment by larsoner** [comment]
> I guess you only need to link travis with pip afterwards so the release is pushed to pip when the tests on the master branch finish successful.

Okay let me know when I need to push something (probably private keys to Travis?) to let you keep working on it

**Comment by jan-janssen** [comment]
I created the corresponding PR https://github.com/h5io/h5io/pull/33 . To configure travis to automatically deploy on pypi https://docs.travis-ci.com/user/deployment/pypi/
