### ISSUE TITLE
CircleCI Migration - 1.0 to 2.0

### ISSUE THREAD

**Issue by jan-janssen** [h5io/h5io#38]
`This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. Please start migrating this project to CircleCI 2.0.`

Just saw the message above in https://circleci.com/gh/h5io/h5io/11 - I was not even aware the project is using CircleCI.

**Comment by larsoner** [comment]
There isn't even a CircleCI config. Must have been errantly enabled. I couldn't find a way to remove it in a minute of looking, but there is probably no harm in keeping it.
