### ISSUE TITLE
ENH: convenient method to list datasets (flat) in fh5 file

### ISSUE THREAD

**Issue by dengemann** [h5io/h5io#4]
it's a pain currently with .visit and .visititems -- would be good do have a function that just lists all datasets in a simple and flat manner.

**Comment by Eric89GXL** [comment]
Or at least all datasets that might be readable by `h5io`, i.e. they have a TITLE and the like.

**Comment by dengemann** [comment]
@Eric89GXL we use something like this, taylored to our use case:

```Python
def h5_listdir(fname, max_depth=4):

    datasets = list()

    def _get_dataset(name, member):
        if isinstance(member, h5py.Dataset):
            name_ = '/'.join(name.split('/', max_depth)[:-1])
            if name_ not in datasets:
                datasets.append(name_)

    with h5py.File(fname, 'r') as fid:
        fid.visititems(_get_dataset)

    return datasets
```

**Comment by dengemann** [comment]
Actually it's pretty general.

**Comment by choldgraf** [comment]
What if you had some kind of "describe_h5io_file" function that would parse through all the items readable by h5io, and just output a string description. E.g., if it's a list, say "list of X items". If it's a dict, say "dict, key=X, vals=list of X items" etc.

E.g., right now I pretty much always save things as dictionaries so that I can quickly get a semantic idea of what's inside an h5 file. It'd be nice to be able to just display all dictionary keys without reading in the data.

**Comment by Eric89GXL** [comment]
Sure, feel free to add such a function. It probably should just stay at the top level -- i.e., if the top-level item is a list, just say it's a list with N items. If it's a dict, say it has N keys and then list them. If it's an array, say the dtype and shape. etc.

**Comment by dengemann** [comment]
Yeah!! Mind-sync. +1

**Comment by choldgraf** [comment]
Hey all - I had an extra hour so threw something together for this. What about something like this:

![image](https://cloud.githubusercontent.com/assets/1839645/20896490/ddcb0f9a-bad2-11e6-930c-a6326d74c659.png)

friendly to a PR?

**Comment by dengemann** [comment]
yes!!

**Comment by choldgraf** [comment]
in it's current state I think it should work, though it only goes as deep as 1 level (e.g. you couldn't list out keys/values that are themselves inside of one of the 1st level objects). That OK? It could probably be done pretty easily in a subsequent PR if there'd be a use for it

**Comment by dengemann** [comment]
Yes keep it simple. It's a good ad-hoc tool. There is still the entire HDF5
API if you want more.

**Comment by larsoner** [comment]
We now have list_file_contents
