### ISSUE TITLE
Request: Please create a new version release.

### ISSUE THREAD

**Issue by Aniket-Pradhan** [h5io/h5io#46]
Hello there author(s)!

I was working on [python-mne](https://github.com/mne-tools/mne-python) upgrade for the Fedora OS and encountered some issues with the same. Turns out, h5io is a direct dependency of python-mne and the last few commits you added would help fix the said issues (support for datetime).

I was wondering if you could create a new version release with those changes so that we can incorporate the same in the Fedora OS as quickly as possible.

**Comment by larsoner** [comment]
Let's see if everything automatically works with `versioneer`, I think it's supposed to. Hang tight

**Comment by drammock** [comment]
Looks like it worked!  https://github.com/h5io/h5io/releases/tag/h5io-0.1.2
