### ISSUE TITLE
Attempt to serialize unknown objects

### ISSUE THREAD

**Issue by choldgraf** [h5io/h5io#7]
Maybe this would be too much complexity. But I was thinking it might be useful to add a "serialize" flag, and if the write function didn't recognize the input object's class, it would then try to serialize it with cPickle rather than throw an error. The read function could have something similar, so that in the event that unpickling the data became broken, the user could still read in all the other data. E.g., store them in a node called "pickle_objectname". Doesn't tables do something like this?

**Comment by dengemann** [comment]
not sure but I smell maintenance efforts with this sort of magic API where you guess default stuff. H5py is not necessarily efficient with unfavorable data types. Already list of lists can be terribly slow. This is really a bare bones package for our internal needs, as long as you don't want to make some strong commitments to maintenance keep the profile flat ;) my 2 cents.

**Comment by choldgraf** [comment]
yeah I definitely understand your concerns. I just find myself using h5io more and more often these days because it's a lot easier than writing all your own tables/h5py code. In my mind, it wouldn't require much more maintenance because it's basically a last-ditch effort at storing things in the same object if h5io doesn't know what to do with them.

The mentality would be "if you're saving an unsupported object then we'll try to serialize it for you, but won't go any further" aka, if the serializing doesn't work then it's the user's problem.

An example of how this might be useful: right now there's a discussion about how to handle the I/O for the timegen class. The problem is that there are some things that would be super easy (e.g., the generalization scores, the model parameters, etc) and some things that aren't easy at all (e.g., the CV object in scikit-learn or the model coefficients). With something like this you could just say "store as much of the timegen object as you can easily, and the rest just pickle it".

**Comment by choldgraf** [comment]
Closing this because it doesn't seem like there interest in implementing
