### ISSUE TITLE
Pandas functionality broken

### ISSUE THREAD

**Issue by choldgraf** [h5io/h5io#8]
I just tried testing pandas functionality and am getting errors now. I guess they changed the way that they read/write dataframes to HDF5. When you read back in data with a dataframe, it returns this error:

```
  File "H5F.c", line 1534, in H5Fopen                                                                       
    unable to open file                                                                                     
  File "H5F.c", line 1352, in H5F_open                                                                      
    file close degree doesn't match                                                                         
                                                                                                            
End of HDF5 error back trace                                                                                
                                                                                                            
Unable to open/create file '../../result/connectivity/raw_spec_connectivity/jh17_connectivity_raw.h5' 
```
This is an error within the pytables module, not h5py. I think that h5py/pytables use different methods for closing the files.

**Comment by choldgraf** [comment]
Actually, upgrading to the latest pytables and h5py fixed this for me. Not sure if this is still something that will be a problem or not...

**Comment by Eric89GXL** [comment]
Depends on how stable Pandas keeps their API...

**Comment by choldgraf** [comment]
Yeah - though it looks like this was a tables/h5py issue, not a pandas issue. I didn't change anything in my pandas install. (I think pandas has its own pytables code similar to how mne does externals, so maybe they upgraded it at some point)
