### ISSUE TITLE
Big performance improvements when using arrays vs. lists

### ISSUE THREAD

**Issue by choldgraf** [h5io/h5io#9]
I noticed that you get a big performance improvement when you use an array instead of a list. However, there's no documentation to suggest this in the h5io docstrings or readme. E.g.:

```python
a = range(1000)
b = np.arange(1000)

h5io.write_hdf5('/Users/choldgraf/tmp/test_h5io.h5', a, overwrite=True)
%timeit a = h5io.read_hdf5('/Users/choldgraf/tmp/test_h5io.h5')

h5io.write_hdf5('/Users/choldgraf/tmp/test_h5io.h5', b, overwrite=True)
%timeit b = h5io.read_hdf5('/Users/choldgraf/tmp/test_h5io.h5')
```
outputs:
```
1 loops, best of 3: 276 ms per loop
1000 loops, best of 3: 648 µs per loop
```
That's a couple order of magnitudes faster. There are many cases where it's trivial to use a numpy array instead of a list (e.g., if it's a list of integers or something). So a couple thoughts:

1. At the least, I think it'd be good to include somewhere in the documentation that if possible, store things in arrays instead of a list containing single items (e.g., list of ints, strings, etc).
2. There could also be a "cast_as_array" flag that, will check to see if it sees such a list, and if so, cast it to a numpy array before writing.

Thoughts?

**Comment by Eric89GXL** [comment]
-1 on a flag to do the casting, I think users should do it. Let's improve the docs to mention that iterables like list, tuple, and dict will cause new entries for each item they contain, so it can be (much) slower than arrays for large items.

**Comment by choldgraf** [comment]
sounds good - I think it's fine to tell users this as well, just thought I'd mention the possibility :) what if there were a warning, though? E.g.:
```
if isinstance(item, [list, tuple]):
   if len(item) > 100:
      raise_warning_about_slowness
```
something like that?

**Comment by dengemann** [comment]
I think this is known h5py behavior. I would rather add a doc here, not always it can be cast into an array.

**Comment by Eric89GXL** [comment]
I guess we could. But "slow" is relative, 250ms to load a dataset might not be bad, especially if your list isn't of integers or floats but rather dictionaries or something. So I fear any heuristic we try to write to warn people will fail too often.

**Comment by choldgraf** [comment]
So cool - so just an addition to the docstring of the "write_hdf5" function? Or would you rather it be in a FAQ or subsection of the readme on the github repo?

**Comment by dengemann** [comment]
It can be minutes on nested lists

**Comment by dengemann** [comment]
Why not both?

**Comment by Eric89GXL** [comment]
At least the docstring for now, FAQ if you're really motivated. But I'm not convinced this package is used all that widely so I wouldn't spend too much time on it.

**Comment by choldgraf** [comment]
I didn't mean for the two options to be mutually exclusive :)

and agreed w/r/t time...for example, the reason I ran into this in the first place is because I'm using h5io to package / combine a bunch of smaller files that were created via distributed computing jobs. So sure, it's not a big deal if there's a couple second difference from one method to another. But if you're doing the same operation over 800 files like me, then it can add up.  I couldn't figure out why the I/O was suddenly taking so long, which is what led me to this. I'm just a believer in sharing your pain with others so that they don't have to go through the same thing :)

**Comment by choldgraf** [comment]
also, my guess is that more people will use this over time...most of the matlab people I know are really annoyed when they move to python because the I/O isn't as clear. Pickling is a strange concept for most people, and I think a more or less all-purpose module where you just dump common objects without really thinking about it is useful.

**Comment by choldgraf** [comment]
which is to say, when I tell folks about h5io they usually have some reaction along the lines of "oh, that sounds pretty useful!"

**Comment by choldgraf** [comment]
Is it obvious that I'm going through my backlog of issues / PRs / etc now? :)
